stages:
  - build
  - pack
  - deploy

variables:
  GIT_DEPTH: "1"

build:
  stage: build
  tags:
    - macos
  script:
    # clear this strange error
    - sed -i '' 's/^#if PNG_ZLIB_VERNUM != 0 && PNG_ZLIB_VERNUM != ZLIB_VERNUM/#if 1 == 2/g' source/Irrlicht/libpng/pngpriv.h
    - cd source/Irrlicht/MacOSX/
    - xcodebuild -project MacOSX.xcodeproj
    - cd ../../../
    - cp source/Irrlicht/MacOSX/build/Release/libIrrlicht.a .
  artifacts:
    paths:
      - libIrrlicht.a

pack:
  stage: pack
  tags:
    - linux
  dependencies:
    - build
  script:
    - apt update; apt -y install tar
    - mkdir dist
    - tar -zcvf irrlicht-mycard-mac.tar.gz libIrrlicht.a include
  artifacts:
    paths:
      - dist

upload_to_minio:
  stage: deploy
  dependencies:
    - build
  tags: 
    - pack
  image: python
  script:
    - pip install -U -i https://mirrors.aliyun.com/pypi/simple/ awscli
    - aws s3 --endpoint=https://minio.mycard.moe:9000 cp dist/irrlicht-mycard-mac.tar.gz s3://mycard/ygopro-build-materials/
  only:
    - master
