language: cpp
os: osx
sudo: required
osx_image: xcode8
addons:
  ssh_known_hosts:
  - github.com

script:
- cd source/Irrlicht/MacOSX/
- xcodebuild -project MacOSX.xcodeproj

before_deploy:
- cd ../../../
- cp source/Irrlicht/MacOSX/build/Release/libIrrlicht.a .
- tar -czf irrlicht-mycard-mac.tar.gz libIrrlicht.a include

deploy:
  provider: releases
  file:
  - irrlicht-mycard-mac.tar.gz
  skip_cleanup: true
  on:
    tags: true
  api-key:
    secure: j7YxYAyoQr1albVJIypwloeJXtZMj11FtqmCDyJ8QGiFk2431o0KMNvN1tC2pK/x08ntN5iVzwEfWh7owDSBeu1HDJo7H7w69s5Rt3UfJE4bw5G2RM6PhG8ZQBwIPkXyXULPTjj3YQRFvcPdBusndQVPhFe/staGLa/t+KOzMyw=
