language: cpp
os: osx
sudo: required
osx_image: xcode8
addons:
  ssh_known_hosts:
  - github.com

script:
- cd source/Irrlicht/MacOSX/
- xcodebuild -project MacOSX.xcodeproj

before_deploy:
- cd ../../../
- cp source/Irrlicht/MacOSX/build/Release/libIrrlicht.a .
- tar -czf irrlicht-mycard-mac.tar.gz libIrrlicht.a include

deploy:
  provider: releases
  file:
  - irrlicht-mycard-mac.tar.gz
  skip_cleanup: true
  on:
    tags: true
  api-key:
    secure: gSSbpvW+ebT+lvJfN48DhrgLqd43csB1OGS4NTq/0Fa2oZxEKjwvKOrtuxloCCVh2keRivlBRgIkBID0fRIDahTv4xZel+rOPCaSfGBJpIK1wGT+T2BQnkCumbPxhK2n8rkzcnlariMdnwcEqzgPGKA1S5Sly8rVqe3R3uax1/YIV3a55YxokJisHFmaHDZf/0VMC8FrMYVbU+GgKyFIeHxbjGeNchmfBBWrOiWyR1oEV/sYQTeQcwU1biGArYpVkXHlUhXhv/Z3vChZ7xQw9xAe3G8CS9Z8Pr2w5Zi/85m710CJ/bjlT2nvBL9VgsVwOQYAPxe9Yfuvp2UrkgI8KSwJcxoh+BVSRYvoZeE3LTbxk0Vl+xBkwjlT7OImY5Tz0Z1/jRt8bEyT2czww4CzP/YbD11PROATV/h43h44eJ6XMpNj//QNtdM3CAIF5iK1L926RIEqIi74bIB8k6f8AVw8e8x5XKCN3OkY9mvqVi+2QpbJ/2bkETiOcXFlGHzpW2QTdZqYiar5Vq/AVRLOf3JlMEljhoK+mfGYmdlT1qi/j1qG0G5atPElcbOKNofxrvafbEGLkGPYqjVppCUpX9oG2DhWL7nDrkyGItxORwcU8RdLPCBMHq2qVsRfreLY7vc7fzc8uCMoLf5DVyy2BUkhJQzjBazeDrmxJLQOFT8=
