language: cpp
os: osx
sudo: required
osx_image: xcode8
addons:
  ssh_known_hosts:
  - github.com

script:
- cd source/Irrlicht/MacOSX/
- xcodebuild -project MacOSX.xcodeproj

before_deploy:
- cd ../../../
- cp source/Irrlicht/MacOSX/build/Release/libIrrlicht.a .
- tar -czf irrlicht-mycard-mac.tar.gz libIrrlicht.a include

deploy:
  provider: releases
  file:
  - irrlicht-mycard-mac.tar.gz
  skip_cleanup: true
  on:
    tags: true
  api-key:
    secure: X22IWEu7sC1TlvE8BHRIEpEscYLPe2dPQl9Xmw050FnKTeJSaFKtRMI7008RAhx6l0blQ0IpJe+uieLNwPkYoNhbSKerpwPj9/e6fT1k787u3QqYiFFitD/1p849XT58IPYgltVwpk8yaXvd1keBiLfnqaKuJe7uPJkOR2G+EFTTmB5Fxg6Xl3eDsN23HiCvRGS/Hjw/DDlIXY3GkjGEnSKIaILTgJFY2z/7wjuGy/sOGKylGZseINzOE/f7o+gsZaY9/Bskv+0z0DTE31Z5stfCKIfLi1Y9ZXNEy8oXG4lg1FBYdqYQKPXUv99VVrhDl5FlcFlcK+EEU42KEFwQQaW0GlCqH2MvUKgnECbdKWz86beFNrtWhP3uS3263NJpu2yXI5lssG4JtgElS2ete9ibvHe7hmGk84RdzcctUlFLGY5WpDCLzffZ0lMIm13uWb4sSgxr3drO7KSixTgAZw/fRf+v/uKvd0xDbJOIKioxRE8CpJHdtqAOQAcaDwRTc9IBwbSPewKcphBeRonBHc5dcxmaHTsp8VgzkdHqHM87nuzibgdvE4N/EXf79gTVDrFuBYn1x0FHQrXomcDM8H/PVk9w+SnL6zGPryxsMMtcl/OHh91KKVWUIXOgxzx4MBbRng3YUl3XptzRx3xEKZfGkiXNThErRmkZP+ncvCA=
