language: cpp
os:
- osx
sudo: required
osx_image: xcode10.1
git:
  submodules: false
addons:
  ssh_known_hosts:
  - github.com
before_install:
#- brew update; brew install freetype
- curl --retry 5 --connect-timeout 30 --location --remote-header-name --remote-name http://downloads.sourceforge.net/irrlicht/irrlicht-1.8.4.zip; unzip -q irrlicht-1.8.4.zip
- cp -r irrlicht-1.8.4/source/Irrlicht/MacOSX source/Irrlicht/
- cp -r irrlicht-1.8.4/source/Irrlicht/CD3D8* source/Irrlicht/

script:
- cd source/Irrlicht/MacOSX/
- xcodebuild -project MacOSX.xcodeproj
#before_deploy:
#- cp build/Release/libIrrlicht.a /usr/local/lib/ ;  cp -r ../../../include /usr/local/include/irrlicht ; cd ../../../../
#deploy:
#  provider: releases
#  file:
#  - irrlicht-mycard-mac.tar.gz
#  skip_cleanup: true
#  on:
#    tags: true
#  api-key:
#    secure: j7YxYAyoQr1albVJIypwloeJXtZMj11FtqmCDyJ8QGiFk2431o0KMNvN1tC2pK/x08ntN5iVzwEfWh7owDSBeu1HDJo7H7w69s5Rt3UfJE4bw5G2RM6P#hG8ZQBwIPkXyXULPTjj3YQRFvcPdBusndQVPhFe/staGLa/t+KOzMyw=
branches:
  only:
  - master
  - mac-1.8.4
