language: cpp
os: osx
sudo: required
osx_image: xcode8
addons:
  ssh_known_hosts:
  - github.com

script:
- cd source/Irrlicht/MacOSX/
- xcodebuild -project MacOSX.xcodeproj

before_deploy:
- cd ../../../
- cp source/Irrlicht/MacOSX/build/Release/libIrrlicht.a .
- tar -czf irrlicht-mycard-mac.tar.gz libIrrlicht.a include

deploy:
  provider: releases
  file:
  - irrlicht-mycard-mac.tar.gz
  skip_cleanup: true
  on:
    tags: true
  api-key:
    secure: NUuVEofSSOTeEx/bvrTBi5AprOyXzdniAY9q39FlZaKc3MwkFQofH4XnNbaceF2OcPvAvl63qTugy8bP5BmIKpAvBpgQGuEwE38zoxDAlWI4ZUGr3xsU6MVmt1jNy0iNnnbZQB5vvcGl1rQ/xm3MFGLgqE2Scq8oSPS2SFCrcff/xcyJkBhGjqe9QWqPlWFG93nE2APW3IvCN1oRL42HAkT6cyzcIyfeS3UZZLoBj2hyx7FdE9jyHAbFWnn3azfmvcncCFjFl3S3cF4kfzLNwgY09NawwEKDUsqJXuJA7Xo13Jsg/JhCRaqlgSx1WOhTdd4K7/+wqaKSiQEZqSODlukaXI96oc9bX+O0ir1O2G5jRzN0+O4fwVI9/WopDB6llKanPyRl7STamFx1tZwceclSQ4ascy3qm2zX6NpGVT1Hy4NIsG9wnpJIl1YrjGkgFn8qZ+oZCM7MBN27VRU/8pRKfRBJ0eQo0TafKinIuAUm422w6iM7uGrtEFdUQNWOCN+QgiqyXpYRkFAN+qXa8WKvtZwzZTcu7ZDzkjfCjUY8CAaopTxVrk7kupqpIreX/xFmLWbXbnUOaBD+pz9H1yO11oAT5bkvgAceEIy8RSwVFX2e1MVaLGaBI3cwafKnaLguF4N2us2G+sSia4ANV2MwpirHFsSoPB7/tx7j1LI=
