language: cpp
os: osx
sudo: required
osx_image: xcode8
addons:
  ssh_known_hosts:
  - github.com

script:
- cd source/Irrlicht/MacOSX/
- xcodebuild -project MacOSX.xcodeproj

before_deploy:
- cd ../../../
- cp source/Irrlicht/MacOSX/build/Release/libIrrlicht.a .
- tar -czf irrlicht-mycard-mac.tar.gz libIrrlicht.a include

deploy:
  provider: releases
  file:
  - irrlicht-mycard-mac.tar.gz
  skip_cleanup: true
  on:
    tags: true
  api-key:
    secure: "jKRS17HCPYuJRJrQkRAGFMexCb4o2h0Pf0aVarO5LAMj6nmPB3qa8vNFildEnlgEbiLavJHAhRxtLiFIifsIbhStCTuLCiPmWozEgd+BP/MtVy10hikrcFGjx6pyxtTpFG88bqRhdi2wNKv/jtqhSI3ZgtN09qp+E+qWE0QS06rW0HE9DAH+NPeOX60NUTQXeOwPnQ2LXh0LB5haAqvlh9UaxvGSmkFnrwpju7VlFcD1Hrudq1XcsuuTDSdkrfrFMZPrPX/1YjHatU5Nye/MnGgwmZNV9KbCtXA+lZ0jJ7gGylcLbhLAF/nlHpZSWZVWyRTdvbz3P5by4UddhMYdpnarqh9oFTQWS0HX7kEoQXOqSHa0XplpSxi3J806cQJxI3lbEWMLxTDrS9q6XFewlPOnyrZEUQnhQMqytA/t+p1aIfmGItJpx+SuFhAX3mHsdIOMbna5hYfsd7ye9D+apCkVgLIxyPyW2Yyhpii3flx6EtFrTb3TZ1JtH5mhxX7VgcFOV+fURBvmhPARSE2s4+8cAn6RB7VWDB6tArvlSOrjfID3BJQIui79YKfv/cLdfi+8nzyI1QYgO0bTUvA1uCiUwJCFuAHpIlb+JWpuMjCeJB77YjJ2wkG+FrIfaRGYxgk5YBRYt33ClYTxHjd5Ytc+UEp+pTuxNDrlSs/hcXU="
